name: selfsupmotion
channels:
  - pytorch
  - conda-forge
dependencies:
  - albumentations
  - bzip2
  - cython
  - ddt
  - flake8
  - flake8-docstrings
  - gitdb
  - gitpython
  - h5py
  - imageio-ffmpeg
  - lz4
  - matplotlib
  - mlflow
  - natsort
  - numpy
  - opencv
  - pandas
  - pillow
  - pip
  - pytest
  - pytorch>=1.8
  - pyturbojpeg
  - pyyaml
  - scikit-learn
  - torchvision
  - tqdm
  - umap-learn
  - pip:
    - deco
    - frozendict
    - orion>=0.1.8
    - pytorch-lightning>=1.3.0
    - pytorch-lightning-bolts
    - sphinx
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
    - sphinxcontrib-katex
    - tensorflow-cpu
    - recommonmark
