batch_size: 160
optimizer: sgd
learning_rate: 0.03
start_lr: 0.00001
final_lr: 0.000001
warmup_epochs: 3
max_epoch: 50
patience: 15
weight_decay: 0.0005
lars_wrapper: False
temperature: 0.1
architecture: simsiam
backbone: resnet50
hidden_mlp: 2048
feat_dim: 256
first_conv: True
maxpool1: True
exclude_bn_bias: False
input_height: 224
tuple_length: 2
frame_offset: 1
tuple_offset: 1
exp_name: pretrain_baseline_sgd
gpus: 1
num_workers: 4
seed: None
precision: 16
early_stop_metric: val_loss
gaussian_blur: True
jitter_strength: 1.0
shared_transform: True
crop_height: "auto"
crop_scale_min: 0.5
crop_scale_max: 1.0
crop_ratio_min: 0.85
crop_ratio_max: 1.17
crop_strategy: centroid
sync_hflip: True
keep_only_frames_with_valid_kpts: False
use_hflip_augment: False
resort_keypoints: False
