batch_size: 512
optimizer: sgd
learning_rate: 0.03
weight_decay: 0.0005
lars_wrapper: False
temperature: 0.1
architecture: simsiam
backbone: resnet18
hidden_mlp: 512
feat_dim: 512
patience: 5
max_epoch: 50
exp_name: simsiam_96x96_test
gpus: 1
num_workers: 16
seed: None
precision: 32 #16-bit is unstable!!!
image_size: 96
pairing: next
early_stop_metric: val_accuracy


